In [4]:
import numpy as np

a = np.array([1, 2, 3])
print(a)
b = np.array([[1, 2], [3, 4]])
print(b)
c=[1,2,3]

[1 2 3]
[[1 2]
 [3 4]]


In [6]:
type(b)

numpy.ndarray

In [7]:
ary = np.zeros(5)
print(ary)

[0. 0. 0. 0. 0.]


In [8]:
ary = np.arange(2,11,2)
print(ary)

[ 2  4  6  8 10]


In [11]:
ary1=np.array([2,4,6 ])
ary2=np.array([10,20,30])
print(ary1*ary2)
result = ary1*ary2

[ 20  80 180]


In [12]:
filtered = result[result>20]
print(filtered)

[ 80 180]


In [13]:
import pandas as pd

In [17]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [18]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [19]:
df.to_csv('output_students.csv', index=False)

In [24]:
df = pd.read_csv('output_students.csv')
print(df.head())
df.info()
df.describe()

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      3 non-null      object
 1   나이      3 non-null      int64 
 2   성별      3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


나이
count   3.000000
mean   27.333333
std     2.516611
min    25.000000
25%    26.000000
50%    27.000000
75%    28.500000
max    30.000000